dependencies {
    api(projects.modulesDepositEventEndpointApplicationModel)
    api(libs.pillar.web.api.utils)
    api(libs.pillar.json.serialization.ddd)

    implementation(projects.modulesDepositEventEndpointAdaptersDrivingHttpSerializationJson)
    implementation(libs.acme.schema.catalogue.json.common)
    implementation(libs.pillar.json.serialization.correlation.core)
    implementation(libs.swissknife.lens.core.extensions)
    implementation(libs.swissknife.json.utils)
    implementation(libs.swissknife.configuration.utils)
    implementation(libs.swissknife.logging.standard.slf4j.configuration)
    implementation(libs.swissknife.kotlin.extensions)
    implementation(libs.pillar.json.serialization.web.api)
    implementation(libs.pillar.json.serialization.pagination)

    testImplementation(projects.modulesDepositEventEndpointDomainTestUtils)
    testImplementation(libs.pillar.json.serialization.test.utils)
    testImplementation(libs.swissknife.ddd.test.utils)
    testImplementation(libs.swissknife.test.utils)
    testImplementation(libs.pillar.web.api.test.utils)
    testImplementation(libs.swissknife.openapi.checking.test.utils)
    testImplementation(libs.swissknife.correlation.core.test.utils)
    testImplementation(libs.pillar.correlation.logging.test.utils)
    testImplementation(libs.swissknife.resource.utils)
    testImplementation(libs.swissknife.openapi.validation.http4k.test.utils)
    testImplementation(libs.swissknife.pagination.test.utils)
}